### ISSUE TITLE
Extension doesn't do anything, produces vague error

### ISSUE THREAD

**Issue by daisylb** [microsoft/vscode-anycode#80]
Every time I try to use anycode with anycode-python, I get the following:

```
[Error - 12:06:54] Unhandled exception
[Error - 12:06:54] [object Object]
```

I'm not quite sure where to start debugging this, since the error message is so vague. I guess that [this code here](https://github.com/microsoft/vscode-anycode/blob/26947588357c6256d50d0c59155ad16e4783c7a7/anycode/server/src/node/main.ts#L12-L13) needs to be changed so that it produces a more explanatory output message to start with?

I've tried to edit it locally in order to debug the underlying issue, but I can't find a corresponding file in the `~/.vscode/extensions/ms-vscode.anycode-0.0.72/` directory.

This started happening on a very large Python codebase (the reason I'm using anycode in the first place is because this codebase is so large that Pyright's "go to symbol in workspace" is so slow that it's basically non-functional) but I'm able to reproduce this on a much smaller Python project (a single Python file).

**Comment by jrieken** [comment]
This should now be fixed with version 0.0.73

**Comment by daisylb** [comment]
Sweet! Just confirming that this works now.

I do still get an `[object Object]` being logged (see below), but the root problem of go to symbol not working has been solved :D 

```
[INDEX] using 58999 of 58999 files for **/*.{py,rpy,pyw,cpy,gyp,gypi,pyi,ipy}
[index] initializing index for 58999 files.
[Error - 15:54:04] [object Object]
[index] added FROM CACHE 0 files 11.60ms, all need revalidation, 58999 files are NEW, 0 where OBSOLETE
[index] unleashed files matching: python
```
